feat: #108 file size included in the current search
Ferlab-Ste-Justine/cqdg-portal-ui-deprecated pull request #63
Opened 2020-12-03 21:41 UTC by kjacqueschu

![image](https://user-images.githubusercontent.com/74249528/101091606-63baac00-3586-11eb-9705-d12da1b0b876.png)
![image](https://user-images.githubusercontent.com/74249528/101091653-746b2200-3586-11eb-84ce-ed578415136c.png)

2020-12-03 22:01 UTC, francisl requested changes
console.log(👻 )

2020-12-03 22:01 UTC, francisl commented on src/packages/@cqdg/pages/FileRepository/FilesTable/FilesTable.js
> +    console.log(fileSummary, formatFileSize(fileSummary.file_size.stats.sum, {}, EFileInputType.MB));
😨

2020-12-03 22:01 UTC, francisl commented on src/packages/@cqdg/utils/formatFileSize.ts
> +  const baseConversion = 1000;
top assignation since it wont ever be mangle inside function call and then set only once in the program lifetime?

2020-12-03 22:08 UTC, kjacqueschu commented on src/packages/@cqdg/pages/FileRepository/FilesTable/FilesTable.js
> +    console.log(fileSummary, formatFileSize(fileSummary.file_size.stats.sum, {}, EFileInputType.MB));
je vais l'ajouter au projet les console.log interdit xD un pre hook commit haha (bientot)

2020-12-04 14:53 UTC, francisl approved these changes
:shipit:

2020-12-04 14:53 UTC, merged